# Generated by Django 4.1.7 on 2023-02-18 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('tipologia', models.CharField(max_length=50)),
                ('titular', models.CharField(max_length=255)),
                ('inversion', models.DecimalField(decimal_places=4, max_digits=10)),
                ('ingreso', models.DateField()),
                ('estado', models.CharField(max_length=50)),
            ],
        ),
    ]
