# Generated by Django 4.1.7 on 2023-02-18 04:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=300)),
                ('post_code', models.CharField(max_length=10)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('free_bikes', models.IntegerField()),
                ('has_ebikes', models.BooleanField()),
                ('normal_bikes', models.IntegerField()),
                ('slots', models.IntegerField()),
                ('empty_slots', models.IntegerField()),
                ('payment', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('none', 'None'), ('transitcard', 'Transit Card'), ('creditcard', 'Credit Card'), ('phone', 'Phone')], max_length=20), default=list, size=None)),
                ('payment_terminal', models.BooleanField()),
                ('renting', models.BooleanField()),
                ('returning', models.BooleanField()),
                ('last_updated', models.DateTimeField()),
                ('uid', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
